server:
  port: 9090
spring:
  application:
    name: dba-professor
  config: 
    import: optional:configserver:http://localhost:8888
  # Configuración de Memcached
  cache:
    type: memcached
memcached:
  servers: localhost:11211
  protocol: binary
  operation-timeout: 3000
# Conexión con Eureka
eureka: 
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka